apiVersion: apps/v1
kind: Deployment
metadata:
  name:  sensor
  labels:
    app:  sensor
spec:
  selector:
    matchLabels:
      app: sensor
  replicas: 1
  template:
    metadata:
      labels:
        app:  sensor
    spec:
      containers:
      - name:  sensor
        image:  izderadicka/sensor:latest
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 200m
            memory: 400Mi
        livenessProbe:
          httpGet:
            path: /q/health/live
            port: 5501
          initialDelaySeconds: 15
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /q/health/ready
            port: 5501
          initialDelaySeconds: 15
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
          periodSeconds: 10
        ports:
        - containerPort:  5501
          name:  http-rest-api
        env:
        - name: QUARKUS_OTEL_EXPORTER_OTLP_ENDPOINT
          value: {{ .Values.otel_collector.url}}
      restartPolicy: Always